# Generated by Django 3.1.4 on 2020-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapp',
            name='name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
