# Generated by Django 3.1.4 on 2020-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApps', '0002_customerapp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapp',
            name='token',
            field=models.CharField(default='test', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerapp',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
