# Generated by Django 3.1.4 on 2020-12-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApps', '0005_auto_20201208_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapp',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
