# Generated by Django 3.1.4 on 2020-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApps', '0006_auto_20201208_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapp',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WARNING', 'Warning'), ('SUSPENDED', 'Suspended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerapp',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
