# Generated by Django 3.1.4 on 2020-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApps', '0008_auto_20201208_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapp',
            name='client',
            field=models.CharField(default='t', max_length=20),
        ),
    ]
