# Generated by Django 3.1.4 on 2020-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApps', '0009_customerapp_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapp',
            name='client',
            field=models.CharField(max_length=20),
        ),
    ]
